import { Check, CheckCheck, ChevronRight, ExternalLink, FileText, List, MoreVertical, Phone, Play, ShoppingBag } from "lucide-react";
import type { DeliveryStatus, Message, Sender } from "./model";

const classes = (...items: Array<string | false | undefined>) => items.filter(Boolean).join(" ");

function Status({ status }: { status?: DeliveryStatus }) {
  if (!status) return null;
  return status === "sent" ? <Check size={13} /> : <CheckCheck size={14} className={status === "read" ? "text-sky-500" : ""} />;
}

function Bubble({ from, time, status, children, wide = false }: { from: Sender; time: string; status?: DeliveryStatus; children: React.ReactNode; wide?: boolean }) {
  const mine = from === "me";
  return (
    <div className={classes("flex w-full", mine ? "justify-end" : "justify-start")}>
      <div className={classes("wa-bubble relative rounded-[9px] px-2.5 pb-1.5 pt-2 shadow-sm", mine ? "rounded-tr-none bg-[#d9fdd3]" : "rounded-tl-none bg-white", wide ? "w-[88%]" : "max-w-[84%]")}>
        <span className={classes("absolute top-0 h-0 w-0", mine ? "-right-2 border-b-[11px] border-l-[8px] border-b-transparent border-l-[#d9fdd3]" : "-left-2 border-b-[11px] border-r-[8px] border-b-transparent border-r-white")} />
        <div className="whitespace-pre-wrap break-words text-[13.5px] leading-[19px] text-[#111b21]">{children}</div>
        <div className="mt-0.5 flex items-center justify-end gap-1 text-[10px] text-[#667781]"><span>{time}</span>{mine && <Status status={status ?? "sent"} />}</div>
      </div>
    </div>
  );
}

function Action({ icon, label, href }: { icon: React.ReactNode; label: string; href?: string }) {
  const content = <><span className="text-[#00a884]">{icon}</span><span className="truncate">{label}</span></>;
  return href ? <a className="flex flex-1 items-center justify-center gap-2 border-t border-[#e9edef] px-2 py-2 text-[12px] font-medium text-[#00a884]" href={href} target="_blank" rel="noreferrer">{content}</a> : <button className="flex flex-1 items-center justify-center gap-2 border-t border-[#e9edef] px-2 py-2 text-[12px] font-medium text-[#00a884]" type="button">{content}</button>;
}

function MediaPlaceholder({ kind }: { kind: "image" | "video" }) {
  return <div className="flex h-36 items-center justify-center rounded-md bg-gradient-to-br from-slate-200 to-slate-300 text-4xl">{kind === "image" ? "🖼️" : "🎬"}</div>;
}

function MessageBody({ message, onUpdate }: { message: Message; onUpdate: (patch: Partial<Message>) => void }) {
  switch (message.type) {
    case "text": return <Bubble {...message}>{message.text}</Bubble>;
    case "media_image": return <Bubble {...message} wide><div className="space-y-1.5">{message.dataUrl ? <img className="max-h-64 w-full rounded-md object-cover" src={message.dataUrl} alt="Uploaded message" /> : <MediaPlaceholder kind="image" />}{message.caption && <div>{message.caption}</div>}</div></Bubble>;
    case "media_video": return <Bubble {...message} wide><div className="space-y-1.5">{message.dataUrl ? <video className="max-h-64 w-full rounded-md bg-black" src={message.dataUrl} controls /> : <MediaPlaceholder kind="video" />}{message.caption && <div>{message.caption}</div>}</div></Bubble>;
    case "media_pdf": return <Bubble {...message} wide><div className="flex items-center gap-3 rounded-md bg-[#f0f2f5] p-2"><span className="grid h-10 w-10 place-items-center rounded-md bg-red-100 text-red-600"><FileText size={20} /></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium">{message.filename}</span><span className="text-[10px] text-[#667781]">PDF · {message.sizeLabel}</span></span></div></Bubble>;
    case "audio": return <Bubble {...message} wide><div className="flex items-center gap-2 py-1"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#00a884] text-white"><Play size={15} fill="currentColor" /></span><span className="h-1 flex-1 rounded bg-slate-300" /><span className="text-[10px] text-[#667781]">{message.durationLabel}</span>{message.dataUrl && <audio className="hidden" src={message.dataUrl} />}</div></Bubble>;
    case "link": return <Bubble {...message} wide><a className="block overflow-hidden rounded-md bg-[#f0f2f5]" href={message.url} target="_blank" rel="noreferrer">{message.thumbnailUrl ? <img className="h-28 w-full object-cover" src={message.thumbnailUrl} alt="Link preview" /> : <div className="grid h-20 place-items-center bg-gradient-to-br from-emerald-100 to-teal-200 text-3xl">🔗</div>}<span className="block p-2"><span className="block text-xs font-semibold">{message.title}</span><span className="mt-0.5 block text-[11px] text-[#667781]">{message.description}</span><span className="mt-1 block truncate text-[10px] text-[#00a884]">{message.url}</span></span></a></Bubble>;
    case "quick_reply": return <div className={classes("flex flex-col", message.from === "me" ? "items-end" : "items-start")}><Bubble {...message}>{message.prompt}</Bubble><div className="mt-1.5 grid w-[84%] gap-1.5">{message.options.map((option, index) => <button key={`${option}-${index}`} type="button" onClick={() => onUpdate({ selectedIndex: index } as Partial<Message>)} className={classes("rounded-lg bg-white px-3 py-2 text-xs font-medium text-[#00a884] shadow-sm", message.selectedIndex === index && "text-slate-400")}>{option}</button>)}</div></div>;
    case "list": return <Bubble {...message} wide><div>{message.prompt}</div><div className="-mx-2.5 mb-[-6px] mt-2 overflow-hidden rounded-b-[9px] border-t border-[#e9edef] bg-white"><div className="px-3 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-wide text-[#667781]">{message.sectionTitle}</div>{message.items.map((item) => <div key={item.id} className="flex items-center gap-2.5 border-t border-[#f0f2f5] px-3 py-2"><span className="text-lg">{item.emoji || "•"}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-medium">{item.title}</span><span className="block truncate text-[10px] text-[#667781]">{item.description}</span></span><ChevronRight size={14} className="text-[#8696a0]" /></div>)}<button type="button" className="flex w-full items-center justify-center gap-2 border-t border-[#e9edef] px-3 py-2.5 text-xs font-medium text-[#00a884]"><List size={15} />{message.buttonLabel || "View all"}</button></div></Bubble>;
    case "cta": return <div className={classes("flex", message.from === "me" ? "justify-end" : "justify-start")}><div className="w-[84%] overflow-hidden rounded-[9px] bg-white shadow-sm"><div className="px-2.5 pb-1 pt-2 text-[13.5px]">{message.text}</div><div className={classes("grid", message.buttons.length > 1 && "grid-cols-2")}>{message.buttons.map((button) => <Action key={button.id} icon={button.kind === "url" ? <ExternalLink size={14} /> : <Phone size={14} />} label={button.label} href={button.kind === "url" ? button.value : `tel:${button.value}`} />)}</div><div className="flex items-center justify-end gap-1 px-2 pb-1 text-[10px] text-[#667781]">{message.time}{message.from === "me" && <Status status={message.status} />}</div></div></div>;
    case "carousel": return <div><Bubble {...message}>{message.intro}</Bubble><div className="no-scrollbar mt-1.5 flex snap-x gap-2 overflow-x-auto pb-1">{message.cards.map((card) => <article key={card.id} className="w-[78%] shrink-0 snap-start overflow-hidden rounded-[9px] bg-white shadow-sm">{card.imageUrl ? <img className="h-32 w-full object-cover" src={card.imageUrl} alt={card.title} /> : <div className="grid h-32 place-items-center bg-gradient-to-br from-orange-100 via-rose-100 to-violet-200 text-4xl"><ShoppingBag size={38} className="text-rose-500" /></div>}<div className="px-3 py-2"><div className="text-xs font-semibold">{card.title}</div><div className="mt-1 text-[10px] leading-4 text-[#667781]">{card.body}</div></div><Action icon={<ExternalLink size={14} />} label={card.ctaLabel} href={card.productUrl} /></article>)}</div></div>;
    case "flow": return <Bubble {...message} wide><div className="font-semibold">{message.title}</div><div className="mt-1 text-[11px] text-[#667781]">{message.body}</div><div className="mt-2 space-y-1.5">{message.fields.map((field) => <div key={field.id} className="rounded-md bg-[#f0f2f5] px-2 py-1.5"><div className="text-[10px] font-medium">{field.label}{field.required ? " *" : ""}</div><div className="text-[10px] text-[#8696a0]">{field.fieldType === "radio" ? (field.options ?? []).join(" · ") : field.placeholder}</div></div>)}</div><button type="button" onClick={() => onUpdate({ submitted: true } as Partial<Message>)} className="mt-2 w-full rounded-md bg-[#00a884] px-2 py-2 text-xs font-semibold text-white">{message.submitted ? "Submitted" : message.submitLabel}</button></Bubble>;
    case "multiselect": return <Bubble {...message} wide><div>{message.prompt}</div><div className="mt-2 space-y-1">{message.options.map((option) => { const selected = (message.selectedOptionIds ?? []).includes(option.id); return <button key={option.id} type="button" onClick={() => onUpdate({ selectedOptionIds: selected ? (message.selectedOptionIds ?? []).filter((id) => id !== option.id) : [...(message.selectedOptionIds ?? []), option.id] } as Partial<Message>)} className="flex w-full items-center gap-2 rounded-md bg-[#f0f2f5] px-2 py-1.5 text-left text-xs"><span className={classes("grid h-4 w-4 place-items-center rounded border", selected && "border-[#00a884] bg-[#00a884] text-white")}>{selected && <Check size={11} />}</span>{option.label}</button>; })}</div></Bubble>;
  }
}

export function PhonePreview({ contactName, statusLine, messages, selectedId, onSelect, onUpdate }: { contactName: string; statusLine: string; messages: Message[]; selectedId: string | null; onSelect: (id: string) => void; onUpdate: (id: string, patch: Partial<Message>) => void }) {
  return <div className="phone-shell mx-auto w-full max-w-[390px] overflow-hidden rounded-[30px] border-[7px] border-[#1f2933] bg-[#efeae2] shadow-2xl"><div className="flex h-7 items-center justify-center bg-[#1f2933]"><span className="h-1.5 w-20 rounded-full bg-slate-600" /></div><header className="flex items-center gap-2 bg-[#008069] px-3 py-2.5 text-white"><span className="grid h-9 w-9 place-items-center rounded-full bg-white/20 text-sm font-semibold">{contactName.trim().slice(0, 1).toUpperCase() || "C"}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{contactName || "Contact"}</span><span className="block truncate text-[10px] text-white/80">{statusLine || "online"}</span></span><Phone size={17} /><MoreVertical size={17} /></header><div className="wa-wallpaper h-[650px] overflow-y-auto px-4 py-4"><div className="space-y-3">{messages.map((message) => <button key={message.id} type="button" onClick={() => onSelect(message.id)} className={classes("block w-full rounded-xl text-left outline-none transition", selectedId === message.id && "ring-2 ring-[#00a884] ring-offset-2 ring-offset-transparent")}><MessageBody message={message} onUpdate={(patch) => onUpdate(message.id, patch)} /></button>)}{messages.length === 0 && <div className="grid h-80 place-items-center text-center text-sm text-[#667781]">Add a message to start your conversation.</div>}</div></div><footer className="flex items-center gap-2 bg-[#f0f2f5] p-2"><div className="flex-1 rounded-full bg-white px-4 py-2 text-xs text-[#8696a0]">Message</div><span className="grid h-9 w-9 place-items-center rounded-full bg-[#00a884] text-white">🎤</span></footer></div>;
}

